### ISSUE TITLE
When switching url previous value is kept instead of new value

### ISSUE THREAD

**Issue by demartsc** [coopermaruyama/tableau-react#1]
Need to add something like below to the initTableau function in order to get newly passed URL to render on submission/click event. 

var vizUrl = nextProps.url || this.getUrl();

**Comment by coopermaruyama** [comment]
Hey, unfortunately I no longer have access to a tableau account that I can use for running the unit tests. Would be great if you can make a PR and `npm test` to make sure everything works. If so, open a PR and I'll merge it.

**Comment by coopermaruyama** [comment]
Is this fixed in 1.1.0?
