### ISSUE TITLE
refreshDataAsync() on interval

### ISSUE THREAD

**Issue by jduysen** [coopermaruyama/tableau-react#35]
I just want to see if there is an out of the box way that I am not seeing to call the refreshDataAsync tableau api function.  As a way to get it working, I put an interval in the componentDidMount method of your TableauReports.js and that seems to work.  I think I will probably also add 'interval' as an optional prop to the component so that I can define the interval on a per component basis.  Let me know if that is functionality that already exists or if I should maybe create a branch to add those features to this library.

Thanks,

James

**Comment by czxtm** [comment]
Hi, I've merged your PR and published at 2.2.0

Thanks!
