### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by fmaldonados** [coopermaruyama/tableau-react#4]
something its happening when i import the component 

this is the error:

 39 | function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
  40 | 
  41 | var propTypes = {
  42 |   filters: _react.PropTypes.object, <----------
  43 |   url: _react.PropTypes.string,
  44 |   parameters: _react.PropTypes.object,
  45 |   options: _react.PropTypes.object,

**Comment by treygeorge** [comment]
I believe this issue would be resolved with this PR:
https://github.com/coopermaruyama/tableau-react/pull/3

If you are using a more recent version of React - proptypes is expected to be imported from its own package and not directly from the React package.

**Comment by psuanm5030** [comment]
I am having a similar issue.  Any chance that the change can be accepted and pushed to the master branch?

**Comment by coopermaruyama** [comment]
Fixed in 1.1.0 sorry for the delay
