### ISSUE TITLE
Incompatible with React 16 and later

### ISSUE THREAD

**Issue by jtiscione** [coopermaruyama/tableau-react#7]
This component has a hard dependency on React 15, and since PropTypes has been moved into a separate module in 16, it won't build. Unfortunately React 15 is listed only as a peer dependency, which means people are going to waste time laboring under the assumption that tableau-react is compatible with the current version of React.
If this project is no longer being maintained I would suggest at least moving React 15 from peerDependencies to dependencies so that people know to stay away.

**Comment by coopermaruyama** [comment]
Fixed in 1.1.0

**Comment by FranciscoKloganB** [comment]
Still getting this in v2.2.0
